import Annoucements from "@/components/layout/Annoucements";
import Footer from "@/components/layout/Footer";
import MobileNav from "@/components/layout/MobileNav";
import Navbar from "@/components/layout/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { ImageKitProvider } from "@imagekit/next";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { DM_Sans, Geist, Geist_Mono, Urbanist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Script from "next/script";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const satoshi = localFont({
  src: "../public/fonts/Satoshi-Variable.ttf",
  variable: "--font-satoshi",
});

const melodrama = localFont({
  src: "../public/fonts/Melodrama-Variable.ttf",
  variable: "--font-melodrama",
});

export const metadata: Metadata = {
  title: "Modaura - Artificial Jewelry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${satoshi.variable} ${urbanist.variable} ${melodrama.variable} ${dmSans.variable} bg-ivory antialiased relative flex flex-col items-center w-screen min-h-dvh`}
      >
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="lazyOnload"
        />
        <SessionProvider>
          <ImageKitProvider
            urlEndpoint={process.env.NEXT_IMAGEKIT_PUBLIC_URL_ENDPOINT}
          >
            <Annoucements />
            <Navbar />
            <MobileNav />
            <main className="font-dmSans min-h-fit w-screen flex flex-col space-y-10 lg:space-y-16 px-5 lg:px-10 items-start justify-start">
              {children}
            </main>
            <Footer />
            <Toaster />
          </ImageKitProvider>
        </SessionProvider>
        <Analytics />
      </body>
    </html>
  );
}
